steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mangstoon/backend:$COMMIT_SHA'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mangstoon/backend:latest'
      - 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mangstoon/backend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mangstoon-backend'
      - '--image'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mangstoon/backend:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/mangstoon/backend'
